//callback functions to simplify DOM lookups and centralize them in one place for easier maintenance and readability. This way, if the structure of the HTML changes, we only need to update the selectors in this file rather than throughout the entire codebase. It also provides a clear and consistent way to access DOM elements across different modules of the app, improving code organization and reducing the likelihood of errors when manipulating the DOM.

const byId = (id) => document.getElementById(id);
const query = (selector) => document.querySelector(selector);

// All DOM lookups live here so feature modules can focus on behavior.
export const dom = {
  documentElement: document.documentElement,
  body: document.body,
  app: byId("app"),
  heroSection: byId("heroSection"),
  stateSection: byId("stateSection"),
  regulationSection: byId("regulationSection"),
  beginButton: byId("beginButton"),
  emotionGrid: byId("emotionGrid"),
  backButton: byId("backButton"),
  resetButton: byId("resetButton"),
  currentStateDisplay: byId("currentState"),
  breathingOrb: byId("breathingOrb"),
  startBreathingButton: byId("startBreathingButton"),
  breathingText: byId("breathingText"),
  breathingCount: byId("breathingCount"),
  breathingPattern: byId("breathingPattern"),
  breathingNote: byId("breathingNote"),
  promptText: byId("promptText"),
  nextPromptButton: byId("nextPromptButton"),
  groundingContent: byId("groundingContent"),
  journalInput: byId("journalInput"),
  saveReflectionButton: byId("saveReflectionButton"),
  reflectionsList: byId("reflectionsList"),
  charCount: byId("charCount"),
  themeToggleButton: byId("themeToggleButton"),
  soundEnabledToggle: byId("soundEnabledToggle"),
  natureSoundToggle: byId("natureSoundToggle"),
  meditationSoundToggle: byId("meditationSoundToggle"),
  guidedMeditationToggle: byId("guidedMeditationToggle"),
  natureSoundSelect: byId("natureSoundSelect"),
  masterVolumeInput: byId("masterVolumeInput"),
  natureVolumeInput: byId("natureVolumeInput"),
  meditationVolumeInput: byId("meditationVolumeInput"),
  guidedMeditationButton: byId("guidedMeditationButton"),
  guidedMeditationText: byId("guidedMeditationText"),
  soundStatus: byId("soundStatus"),
  affirmationText: byId("affirmationText"),
  affirmationMeta: byId("affirmationMeta"),
  newAffirmationButton: byId("newAffirmationButton"),
  routineContent: byId("routineContent"),
  refreshRoutineButton: byId("refreshRoutineButton"),
  stateCountStat: byId("stateCountStat"),
  breathingCountStat: byId("breathingCountStat"),
  journalCountStat: byId("journalCountStat"),
  visitCountStat: byId("visitCountStat"),
  dominantStateStat: byId("dominantStateStat"),
  emotionTimeline: byId("emotionTimeline"),
  fontScaleInput: byId("fontScaleInput"),
  particlesHero: byId("particlesHero"),
  particlesState: byId("particlesState"),
  particlesRegulation: byId("particlesRegulation"),
  customCursor: query(".custom-cursor"),
  cursorFollower: query(".cursor-follower"),
  getAllBodyElements: () => document.body.querySelectorAll("*"),
  getButtons: () => document.querySelectorAll("button"),
  getEmotionCards: () => document.querySelectorAll(".emotion-card"),
};
